---
resources:
  - name: super-app
    type: git
    branch: ci
    source:
      uri: https://github.com/tammymendt/concourse-tutorial.git

jobs:
  - name: Test
    plan:
    - get: super-app
      trigger: true
    - task: Testing
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: ./test_fmt.sh
          dir: super-app/scripts

        inputs:
          - name: super-app
