---

platform: linux
image_resource:
  type: docker-image
  source: {repository: golang}
run:
  path: sh
  args:
  - -exc
  - |
    ./scripts/go_deps.sh
    ./scripts/go_build.sh darwin 0.0.1
    mv super_*_darwin_amd64 ../artifact_darwin
  dir: super-app/
inputs:
  - name: super-app
outputs:
  - name: artifact_darwin
